### ISSUE TITLE
not working!!!

### ISSUE THREAD

**Issue by theompant** [Pixel-Props/redfin#1]
last oct prop is fineaf. the latest nov release not working sir and yes i tried both safe and non safe too.

**Comment by 0x11DFE** [comment]
What's the matter?
Are you running on latest security patch?

**Comment by theompant** [comment]
![Screenshot_20201107-110712](https://user-images.githubusercontent.com/69330741/98433002-735ee600-20e9-11eb-9bea-ac6f2aa29609.png)


> What's the matter?
> Are you running on latest security patch?

yes sir

**Comment by theompant** [comment]
![Screenshot_20201107-111150](https://user-images.githubusercontent.com/69330741/98433125-3810e700-20ea-11eb-9470-7fb673ee1932.png)
last release!

**Comment by 0x11DFE** [comment]
Could you please download [SafetyNet Test](https://play.google.com/store/apps/details?id=org.freeandroidtools.safetynettest) and show me the result?

**Comment by theompant** [comment]
sure sir. once the latest patch will be merged i will try again
