### ISSUE TITLE
SIM Operation Failed

### ISSUE THREAD

**Issue by jd1900** [Pixel-Props/redfin#10]
I've installed this on HentaiOS (which mimics a Pixel 6 PRO - https://t.me/hentaiOS https://wiki.newcentrix.helluvaos.com/) to "downgrade" to Pixel 5 and get Google Photos unlimited storage.
However, it is not working.
I am currently in Android 12 with november security patch but I got the october props. Could that be the problem?

After booting, I don't get the SIM PIN code menu.
Like there is no SIM.
After a while, it appears, and I can't pass it. When entering the right PIN it says "SIM Operation Failed".

**Comment by tahmid8464** [comment]
I flashed this module on ArrowOS Android 11 and Sim cards stopped detecting. I checked my imei and saw that there was no imei. After removing this module, imei came back and sim card started working

**Comment by 0x11DFE** [comment]
Which release was flashed?

**Comment by 0x11DFE** [comment]
Closed until more information provided.
