### ISSUE TITLE
Module isn't working

### ISSUE THREAD

**Issue by 4PERTURE** [Pixel-Props/redfin#2]
Hello, I've always used pixel props, and up till now (November patch) everything has always worked smoothly and with no issues at all.

After the November patch, I've installed both SDK safe and unsafe versions, and none seem to have any effect at all, the fingerprint stays the same and I can't pass safetynet/use some pixel exclusive features.
![Screenshot_20201109-090000](https://user-images.githubusercontent.com/38117317/98520813-8220d680-226a-11eb-8ad2-84b0241dce86.png)
![Screenshot_20201109-090005](https://user-images.githubusercontent.com/38117317/98520824-864cf400-226a-11eb-815e-2475962381f2.png)
![Screenshot_20201109-090419](https://user-images.githubusercontent.com/38117317/98520848-91078900-226a-11eb-9985-8e03ac7f751d.png)

**Comment by 0x11DFE** [comment]
The build number (RD1A.201105.003.C1) on your screenshot does not match with the [201105](https://github.com/Pixel-Props/redfin/releases/tag/201105) build number (RD1A.201105.003.A1)

**Comment by 4PERTURE** [comment]
> The build number (RD1A.201105.003.C1) on your screenshot does not match with the [201105](https://github.com/Pixel-Props/redfin/releases/tag/201105) build number (RD1A.201105.003.A1)
> 
> Edit: If it still does not work you might want to try it yourself.
> 
> RD1A.201105.003 (Japan carriers)
> RD1A.201105.003.A1 (AU/APAC carriers)
> RD1A.201105.003.B1 (EU carriers)
> RD1A.201105.003.C1 (NA/US/Canada carriers)

Should I edit my build number then?

**Comment by 0x11DFE** [comment]
Yes

**Comment by 0x11DFE** [comment]
Please try to flash the module from the [latest release](https://github.com/Pixel-Props/redfin/commit/3ab8a6c62a90b42cd8c71c0dbf85d0b1fb3420a7) again.

**Comment by 4PERTURE** [comment]
> Please try to flash the module from the [latest release](https://github.com/Pixel-Props/redfin/commit/3ab8a6c62a90b42cd8c71c0dbf85d0b1fb3420a7) again.

It's working fine now. Thank you.

![Screenshot_20201112-132613](https://user-images.githubusercontent.com/38117317/98946951-7c3a2800-24ec-11eb-97f1-aa412556001f.png)
![Screenshot_20201112-132607](https://user-images.githubusercontent.com/38117317/98946960-7e03eb80-24ec-11eb-9d9a-4f3f2b806cb0.png)
