### ISSUE TITLE
Safety net fail

### ISSUE THREAD

**Issue by spectkiller** [Pixel-Props/redfin#5]
Device - whyred
ROM - RR 
Android - 10
Magisk - latest canary
Build prop - redfin android 11 January 2021 latest
Issue - safety net fail

Without pixel redfin props, it show safety net pass with "eval type - basic" and after flashing redfin prop, it show safety net fail with "eval type hardware"

![Screenshot_20210125-142745538](https://user-images.githubusercontent.com/37000900/105688128-3f90a100-5f1f-11eb-8865-f9eef9722953.jpg)
![Screenshot_20210125-142622057](https://user-images.githubusercontent.com/37000900/105688138-415a6480-5f1f-11eb-9468-cb1ba94c2d0b.jpg)

**Comment by 0x11DFE** [comment]
SElinux enforcing or permissive?

**Comment by spectkiller** [comment]
> SElinux enforcing or permissive?

enforcing

**Comment by 0x11DFE** [comment]
try to flash [SafetyNet-Fix](https://github.com/kdrag0n/safetynet-fix) else use a official/stable version of your rom.

**Comment by spectkiller** [comment]
will try it in a week

**Comment by 0x11DFE** [comment]
Closed until then.

**Comment by spectkiller** [comment]
Update: Its work. Safety net pass successfully now
