### ISSUE TITLE
Assistant issue

### ISSUE THREAD

**Issue by spectkiller** [Pixel-Props/redfin#6]
Ok google Hotword isn't working after flashing Redfin May props on Android 11 Custom rom Havoc OS with security patch May. 

Using Enforcing Selinux

Using latest Google app with English US language.![Screenshot_20210615-013333_Google.png](https://user-images.githubusercontent.com/37000900/121952714-4018bf80-cd7a-11eb-97f4-f89665abd215.png)

**Comment by 0x11DFE** [comment]
The props are not modifying anything related to the language.
I had the module installed on my vince Havoc-OS all was working correctly.

Does it only happen when you flash the module?
Did you try to change between other languages?

**Comment by spectkiller** [comment]
Well pardon me, i had almost forgot that I have flagged a issue cuz it's been so long. Nowadays I don't use pixel prop, so ig i can't contribute to it anymore.

I kindly request you to close this issue.

Thank you.
